### ISSUE TITLE
Project is now moved to a new maintainer

### ISSUE THREAD

**Issue by simskij** [KopfKrieg/watchtower#7]
Hi KopfKrieg,

After trying for a while I recently got hold of the actual original watchtower repository.
It has now been transfered to https://github.com/containrrr/watchtower. Would you be interested in us merging our projects and combining our efforts on one repo?

Best regards,
Simon

**Comment by KopfKrieg** [comment]
Yes, please :grin: 

Honestly, I haven't done much on my fork. AFAIR I've merged one or two patches and rewrote the Dockerfile (because otherwise I couldn't get autobuilds on Docker Hub working correctly).

Also, do you already have an official repository on Docker Hub?

And how do you want to merge the projects? Should I just create a PR to yours?

**Comment by simskij** [comment]
If you've got the time that would be awesome. I'll add you as a collaborator on the repo

**Comment by simskij** [comment]
Im still working on circleci and dockerhub publishing. :)
Accounts and repos have been created, but that's about it.
